#!/bin/bash

# Tor Client app for YunoHost
# Copyright (C) 2015 Emile Morel <emile@bleuchtang.fr>
# Copyright (C) 2015 Julien Vaubourg <julien@vaubourg.com>
# Contribute at https://github.com/labriqueinternet/torfilter_ynh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#!/bin/bash

ynh_setting() {
  app=${1}
  setting=${2}

  sudo grep "^${setting}:" "/etc/yunohost/apps/${app}/settings.yml" | sed s/^[^:]\\+:\\s*[\"\']\\?// | sed s/\\s*[\"\']\$//
}

domain=$(ynh_setting torfilter domain)
path=$(ynh_setting torfilter path)

tmpdir=$(mktemp -dp /tmp/ torfilter-upgrade-XXXXX)
sudo cp -a /etc/yunohost/apps/torfilter/settings.yml "${tmpdir}/"

export TORFILTER_UPGRADE=1
sudo bash /etc/yunohost/apps/torfilter/scripts/remove &> /dev/null
bash ./install "${domain}" "${path}"

gitcommit=$(ynh_setting torfilter gitcommit)

sudo cp -a "${tmpdir}/settings.yml" /etc/yunohost/apps/torfilter/
sudo rm -r "${tmpdir}/"

sudo yunohost app setting torfilter gitcommit -v "${gitcommit}"

sudo systemctl start ynh-torfilter

exit 0
